// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaTOUpwwpnTbx1CViG37n0lsLNPWT-x8s',
    appId: '1:955185196658:web:26c195054e70430e765ceb',
    messagingSenderId: '955185196658',
    projectId: 'verdant-bank-4d33a',
    authDomain: 'verdant-bank-4d33a.firebaseapp.com',
    storageBucket: 'verdant-bank-4d33a.firebasestorage.app',
    measurementId: 'G-ZPCSS45Q84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoTWLkH4hl138oQHE5M22NA2-mOlsFSkU',
    appId: '1:955185196658:android:954508c22a1f8570765ceb',
    messagingSenderId: '955185196658',
    projectId: 'verdant-bank-4d33a',
    storageBucket: 'verdant-bank-4d33a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN3ifD2-qzuJnjpxFzEEG-Uxe-fOZ56SU',
    appId: '1:955185196658:ios:17be1f358fd50331765ceb',
    messagingSenderId: '955185196658',
    projectId: 'verdant-bank-4d33a',
    storageBucket: 'verdant-bank-4d33a.firebasestorage.app',
    iosBundleId: 'com.example.verdantbank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN3ifD2-qzuJnjpxFzEEG-Uxe-fOZ56SU',
    appId: '1:955185196658:ios:17be1f358fd50331765ceb',
    messagingSenderId: '955185196658',
    projectId: 'verdant-bank-4d33a',
    storageBucket: 'verdant-bank-4d33a.firebasestorage.app',
    iosBundleId: 'com.example.verdantbank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaTOUpwwpnTbx1CViG37n0lsLNPWT-x8s',
    appId: '1:955185196658:web:cd49334ffe1eb797765ceb',
    messagingSenderId: '955185196658',
    projectId: 'verdant-bank-4d33a',
    authDomain: 'verdant-bank-4d33a.firebaseapp.com',
    storageBucket: 'verdant-bank-4d33a.firebasestorage.app',
    measurementId: 'G-PK4DHBXKWM',
  );

}